name: Build & Test

on:
  push:
    branches: [ wizards ]
  pull_request:
    branches: [ wizards ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, osx-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: dotnet test --configuration Release -v n
